development: &defaults
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] || 'nexoos_dev' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  username: <%= ENV['DATABASE_USER'] || 'nexoos' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '123456' %>

test:
  <<: *defaults
  database: nexoos_test

production:
  <<: *defaults
  database: nexoos_prod
